apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: docker.io/waveywaves/mirrord-sqs-debug-example:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ENDPOINT_URL
          value: "http://localstack:4566"
        - name: APP_MODE
          value: "producer"
        - name: FLASK_DEBUG
          value: "1"
        - name: PYTHONUNBUFFERED
          value: "1"
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sqs-producer
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 6002
      targetPort: 5000
  type: ClusterIP 